/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package duckTest;

import org.junit.Test;
import static org.junit.Assert.*;
import duckstype.*;
import ducks.flybehavior.*;

public class AppTest {
    @Test public void testDucks() {
        MallardDuck	mallard = new MallardDuck();
		RubberDuck	rubberDuckie = new RubberDuck();
		DecoyDuck	decoy = new DecoyDuck();
 
		ModelDuck	model = new ModelDuck();

		mallard.performQuack();
		rubberDuckie.performQuack();
		decoy.performQuack();
   
		model.performFly();	
		model.setFlyBehavior(new FlyRocketPowered());
        model.performFly();
        
        assertTrue(true);
    }
}
